name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev
        git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        ~/.rbenv/bin/rbenv init
        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
        echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        ~/.rbenv/bin/rbenv install 3.1.4
        ~/.rbenv/bin/rbenv global 3.1.4
        echo 'export PATH="$HOME/.rbenv/shims:$PATH"' >> ~/.bashrc
        source ~/.bashrc

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
